#ifndef SCIENCE_BRANCH
#define SCIENCE_BRANCH

#ifdef __cplusplus
extern "C" {
#endif

// mathematics & sciences
#define _nabla "∇"
#define _partial "∂"
#define _belongs "∊"
#define _rbelongs "∍"
#define _Belongs "∈"
#define _nBelongs "∉"
#define _rBelongs "∋"
#define _rnBelongs "∌"
#define _QED "∎"
#define _forall "∀"
#define _exist "∃"
#define _nexist "∄"
#define _NULL "∅"
#define _prod "∏"
#define _sum "∑"
#define _plus_or_minus "±"
#define _minus_or_plus "∓"
#define _dot_or_plus "∔"
#define _composite "∘"
#define _dot "∙"
#define _sqrt "√"
#define _prop "∝"
#define _infinity "∞"
#define _vand "∨"
#define _vor "∧"
#define _uand "∪"
#define _uor "∩"
#define _int "∫"
#define _dint "∬"
#define _tint "∭"
#define _oint "∮"
#define _odint "∯"
#define _otint "∰"
#define _cuz "∵"
#define _therefore "∴"
#define _similar "∼"
#define _nsimilar "≁"
#define _congruent "≅"
#define _approxw "≈"
#define _approx "≒"
#define _neq "≠"
#define _equiv "≡"
#define _smaller_or_equal "≤"
#define _greater_or_equal "≥"
#define _subset "⊂"
#define _nsubset "⊄"
#define _rsubset "⊃"
#define _nrsubset "⊅"
#define _subset_or_equal "⊆"
#define _rsubset_or_equal "⊇"
#define _nsubset_and_neq "⊈"
#define _nrsubset_and_neq "⊉"
#define _oplus "⊕"
#define _ominus "⊖"
#define _omult "⊗"
#define _odiv "⊘"
#define _odot "⊙"
#define _vert "⊥"
#define _gaussl "⟦"
#define _gaussr "⟧"
#define _hdots "⋯"
#define _vdots "⋮"
#define _LtoHdots "⋰"
#define _HtoLdots "⋱"

#define _up0 "⁰"
#define _up1 "¹"
#define _up2 "²"
#define _up3 "³"
#define _up4 "⁴"
#define _up5 "⁵"
#define _up6 "⁶"
#define _up7 "⁷"
#define _up8 "⁸"
#define _up9 "⁹"
#define _upa "ᵃ"
#define _upb "ᵇ"
#define _upc "ᶜ"
#define _upd "ᵈ"
#define _upe "ᵉ"
#define _upf "ᶠ"
#define _upg "ᵍ"
#define _uph "ʰ"
#define _upi "ⁱ"
#define _upj "ʲ"
#define _upk "ᵏ"
#define _upl "ˡ"
#define _upm "ᵐ"
#define _upn "ⁿ"
#define _upo "ᵒ"
#define _upp "ᵖ"
#define _upr "ʳ"
#define _ups "ˢ"
#define _upt "ᵗ"
#define _upu "ᵘ"
#define _upv "ᵛ"
#define _upw "ʷ"
#define _upx "ˣ"
#define _upy "ʸ"
#define _upz "ᶻ"
#define _up_lb "⁽"
#define _up_rb "⁾"
#define _up_plus "⁺"
#define _up_minus "⁻"
#define _up_eq "⁼"

#define _down0 "₀"
#define _down1 "₁"
#define _down2 "₂"
#define _down3 "₃"
#define _down4 "₄"
#define _down5 "₅"
#define _down6 "₆"
#define _down7 "₇"
#define _down8 "₈"
#define _down9 "₉"
#define _downa "ₐ"
#define _downe "ₑ"
#define _downh "ₕ"
#define _downi "ᵢ"
#define _downj "ⱼ"
#define _downk "ₖ"
#define _downl "ₗ"
#define _downm "ₘ"
#define _downn "ₙ"
#define _downo "ₒ"
#define _downp "ₚ"
#define _downr "ᵣ"
#define _downs "ₛ"
#define _downt "ₜ"
#define _downu "ᵤ"
#define _downv "ᵥ"
#define _downx "ₓ"
#define _down_lb "₍"
#define _down_rb "₎"
#define _down_plus "₊"
#define _down_minus "₋"
#define _down_equal "₌"

#define _hbar "ℏ"
#define _mho "℧"
#define _degC "℃"
#define _degF "℉"
#define _angstrom "Å"
	
#define _lu_rbrackets "⎛"
#define _lm_rbrackets "⎜"
#define _ld_rbrackets "⎝"
	
#define _ru_rbrackets "⎞"
#define _rm_rbrackets "⎟"
#define _rd_rbrackets "⎠"
	
#define _lu_bbrackets "⎡"
#define _lm_bbrackets "⎢"
#define _ld_bbrackets "⎣"
	
#define _ru_bbrackets "⎤"
#define _rm_bbrackets "⎥"
#define _rd_bbrackets "⎦"
	
#define _lu_cbrackets "⎧"
#define _lmu_cbrackets "⎪"
#define _lm_cbrackets "⎨"
#define _lmd_cbrackets "⎪"
#define _ld_cbrackets "⎩"
	
#define _ru_cbrackets "⎫"
#define _rmu_cbrackets "⎮"
#define _rm_cbrackets "⎬"
#define _rmd_cbrackets "⎮"
#define _rd_cbrackets "⎭"

#define _usum "⎲"
#define _dsum "⎳"

#define _benzene "⌬"

#ifdef __cplusplus
}
#endif

#endif
