#ifndef BOX_MAKER
#define BOX_MAKER

#ifdef __cplusplus
extern "C"{
#endif

#include "win_term_mode.h"

#define _h_line "─"
#define _v_line "│"
#define _lu_corner "┌"
#define _ru_corner "┐"
#define _ld_corner "└"
#define _rd_corner "┘"
#define _l_T "├"
#define _r_T "┤"
#define _T "┬"
#define _rT "┴"
#define _cross_T "┼"
#define _h_bline "━"
#define _v_bline "┃"
#define _lu_bcorner "┏"
#define _ru_bcorner "┓"
#define _ld_bcorner "┗"
#define _rd_bcorner "┛"
#define _l_bT "┣"
#define _r_bT "┫"
#define _bT "┳"
#define _rbT "┻"
#define _cross_bT "╋"
#define _h_dline "═"
#define _v_dline "║"
#define _lu_dcorner "╔"
#define _ru_dcorner "╗"
#define _ld_dcorner "╚"
#define _rd_dcorner "╝"
#define _l_dT "╠"
#define _r_dT "╣"
#define _dT "╦"
#define _rdT "╩"
#define _cross_dT "╬"
#define _ueqv "╒"
#define _vueq "╕"
#define _vdeq "╘"
#define _deqv "╛"
#define _l_pi "╞"
#define _r_pi "╡"
#define _minus_T "╤"
#define _rT_minus "╧"
#define _neq_cross_T "╪"
#define _vvum "╓"
#define _umvv "╖"
#define _vvlm "╙"
#define _lmvv "╜"
#define _v_lT "╟"
#define _v_rT "╢"
#define _piT "╥"
#define _rpi "╨"
#define _vmv "╫"
#define _lu_rcorner "╭"
#define _ru_rcorner "╮"
#define _ld_rcorner "╰"
#define _rd_rcorner "╯"
#define _dot_hline "┄"
#define _dot_vline "┆"
#define _dot_bhline "┅"
#define _dot_bvline "┇"
#define _LtoH "╱"
#define _HtoL "╲"
#define _up "╵"
#define _right "╶"
#define _left "╴"
#define _down "╷"

#define _block "█"
#define _q1_shadow "░"
#define _q2_shadow "▒"
#define _half_shadow "▒"
#define _q3_shadow "▓"
#define _ublock "▀"
#define _dblock "▄"
#define _lblock "▌"
#define _rblock "▐"
#define _lublock "▘"
#define _ldblock "▖"
#define _rublock "▝"
#define _rdblock "▗"

#ifdef __cplusplus
}
#endif

#endif
