#ifndef SPECIAL_FONTS_H
#define SPECIAL_FONTS_H

#ifdef __cplusplus
extern "C"{
#endif

#include "win_term_mode.h"
	
// Cursive
#define _cA "𝓐"
#define _cB "𝓑"
#define _cC "𝓒"
#define _cD "𝓓"
#define _cE "𝓔"
#define _cF "𝓕"
#define _cG "𝓖"
#define _cH "𝓗"
#define _cI "𝓘"
#define _cJ "𝓙"
#define _cK "𝓚"
#define _cL "𝓛"
#define _cM "𝓜"
#define _cN "𝓝"
#define _cO "𝓞"
#define _cP "𝓟"
#define _cQ "𝓠"
#define _cR "𝓡"
#define _cS "𝓢"
#define _cT "𝓣"
#define _cU "𝓤"
#define _cV "𝓥"
#define _cW "𝓦"
#define _cX "𝓧"
#define _cY "𝓨"
#define _cZ "𝓩"
#define _ca "𝓪"
#define _cb "𝓫"
#define _cc "𝓬"
#define _cd "𝓭"
#define _ce "𝓮"
#define _cf "𝓯"
#define _cg "𝓰"
#define _ch "𝓱"
#define _ci "𝓲"
#define _cj "𝓳"
#define _ck "𝓴"
#define _cl "𝓵"
#define _cm "𝓶"
#define _cn "𝓷"
#define _co "𝓸"
#define _cp "𝓹"
#define _cq "𝓺"
#define _cr "𝓻"
#define _cs "𝓼"
#define _ct "𝓽"
#define _cu "𝓾"
#define _cv "𝓿"
#define _cw "𝔀"
#define _cx "𝔁"
#define _cy "𝔂"
#define _cz "𝔃"

// Gothic
#define _gA "𝔄"
#define _gB "𝔅"
#define _gC "ℭ"
#define _gD "𝔇"
#define _gE "𝔈"
#define _gF "𝔉"
#define _gG "𝔊"
#define _gH "ℌ"
#define _gI "ℑ"
#define _gJ "𝔍"
#define _gK "𝔎"
#define _gL "𝔏"
#define _gM "𝔐"
#define _gN "𝔑"
#define _gO "𝔒"
#define _gP "𝔓"
#define _gQ "𝔔"
#define _gR "ℜ"
#define _gS "𝔖"
#define _gT "𝔗"
#define _gU "𝔘"
#define _gV "𝔙"
#define _gW "𝔚"
#define _gX "𝔛"
#define _gY "𝔜"
#define _gZ "ℨ"
#define _ga "𝔞"
#define _gb "𝔟"
#define _gc "𝔠"
#define _gd "𝔡"
#define _ge "𝔢"
#define _gf "𝔣"
#define _gg "𝔤"
#define _gh "𝔥"
#define _gi "𝔦"
#define _gj "𝔧"
#define _gk "𝔨"
#define _gl "𝔩"
#define _gm "𝔪"
#define _gn "𝔫"
#define _go "𝔬"
#define _gp "𝔭"
#define _gq "𝔮"
#define _gr "𝔯"
#define _gs "𝔰"
#define _gt "𝔱"
#define _gu "𝔲"
#define _gv "𝔳"
#define _gw "𝔴"
#define _gx "𝔵"
#define _gy "𝔶"
#define _gz "𝔷"

// Double-Struck
#define _dsA "𝔸"
#define _dsB "𝔹"
#define _dsC "ℂ"
#define _dsD "𝔻"
#define _dsE "𝔼"
#define _dsF "𝔽"
#define _dsG "𝔾"
#define _dsH "ℍ"
#define _dsI "𝕀"
#define _dsJ "𝕁"
#define _dsK "𝕂"
#define _dsL "𝕃"
#define _dsM "𝕄"
#define _dsN "ℕ"
#define _dsO "𝕆"
#define _dsP "ℙ"
#define _dsQ "ℚ"
#define _dsR "ℝ"
#define _dsS "𝕊"
#define _dsT "𝕋"
#define _dsU "𝕌"
#define _dsV "𝕍"
#define _dsW "𝕎"
#define _dsX "𝕏"
#define _dsY "𝕐"
#define _dsZ "ℤ"
#define _dsa "𝕒"
#define _dsb "𝕓"
#define _dsc "𝕔"
#define _dsd "𝕕"
#define _dse "𝕖"
#define _dsf "𝕗"
#define _dsg "𝕘"
#define _dsh "𝕙"
#define _dsi "𝕚"
#define _dsj "𝕛"
#define _dsk "𝕜"
#define _dsl "𝕝"
#define _dsm "𝕞"
#define _dsn "𝕟"
#define _dso "𝕠"
#define _dsp "𝕡"
#define _dsq "𝕢"
#define _dsr "𝕣"
#define _dss "𝕤"
#define _dst "𝕥"
#define _dsu "𝕦"
#define _dsv "𝕧"
#define _dsw "𝕨"
#define _dsx "𝕩"
#define _dsy "𝕪"
#define _dsz "𝕫"
#define _ds0 "𝟘"
#define _ds1 "𝟙"
#define _ds2 "𝟚"
#define _ds3 "𝟛"
#define _ds4 "𝟜"
#define _ds5 "𝟝"
#define _ds6 "𝟞"
#define _ds7 "𝟟"
#define _ds8 "𝟠"
#define _ds9 "𝟡"

#ifdef __cplusplus
}
#endif

#endif
